run:
  timeout: 5m
linters:
  enable:
    - goheader
    - revive
    - deadcode
    - unused
  disable-all: true
# all available settings of specific linters
linters-settings:
  goheader:
    values:
      regexp:
        copyright-year: 202[0-1]
    template-path: code-header-template.txt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: a95f826ff25ddb5968e0dd4e53818a9a35baf016 # only enforce for commits after Jul 15 2021, allows us to phase-in godoc compliance
